Transform: AWS::Serverless-2016-10-31

# TODO: Add tags
# -- tier, type, author, app

Resources:
  etherdome:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Tags:
        AppName: TBD
      Handler: index.handler
      Description: "go-ethereum json-rpc lambda"
      CodeUri: ./etherdome
      # Hack to enforce the correct permissions
      # TODO: Make this permission explicit (?)
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref api
            Path: /
            Method: post
      MemorySize: 1024
      Timeout: 10
  apiauthorizer:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Tags:
        AppName: TBD
      Handler: index.handler
      Description: "Custom authorizer"
      CodeUri: ./authorizer
      MemorySize: 512
      Timeout: 15
  LambdaInvokePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Policy for allowing Lambda Invoke"
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Action:
            - "lambda:InvokeFunction"
            Resource: "*"
  AuthorizerInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - Ref: LambdaInvokePolicy
  AmazonAPIGatewayPushToCloudWatchLogs:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: ""
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
  api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "JSON-RPC API Interface"
        paths:
          "/":
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${etherdome.Arn}/invocations
                responses: {}
              security:
                - authorizer: []
        securityDefinitions:
          authorizer:
            type: apiKey
            name: Authorization
            in: header
            x-amazon-apigateway-authtype: custom
            x-amazon-apigateway-authorizer:
              authorizerUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${apiauthorizer.Arn}/invocations
              identitySource: method.request.querystring.auth
              authorizerResultTtlInSeconds: 300
              authorizerCredentials: !Sub ${AuthorizerInvokeRole.Arn}
              type: request
Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref api
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/Prod'
