Transform: AWS::Serverless-2016-10-31
Resources:
  etherdome:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs6.10
      Handler: index.handler
      Description: "go-ethereum json-rpc lambda"
      CodeUri: ./etherdome
      # Typical run: 584 MB of memory
      MemorySize: 1024
      Timeout: 10
  CustomAuthorizerLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs6.10
      Handler: index.handler
      Description: "Custom authorizer"
      CodeUri: ./authorizer
      MemorySize: 512
      Timeout: 15